FROM nvcr.io/nvidia/pytorch:19.09-py3

LABEL maintainer="wfedorko@triumf.ca"

RUN apt-get update
RUN apt-get --yes upgrade && apt-get --yes install strace locate pydb ddd

RUN pip install xgboost lightgbm seaborn h5py plotly torchviz line_profiler

RUN snap install pycharm-community --classic
RUN snap install code --classic

 
