FROM nvcr.io/nvidia/pytorch:21.02-py3
LABEL maintainer="wfedorko@triumf.ca"

RUN apt-get update
RUN apt-get --yes upgrade && apt-get --yes install strace locate ddd libxtst6 libxtst-dev

RUN apt-get --yes install google-perftools
RUN apt-get --yes install hdf5-tools h5utils libhdf5-dev

COPY pre_config.txt .


#RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true && \
#debconf-set-selections pre_config.txt && \
#echo $DEBIAN_FRONTEND $DEBCONF_NONINTERACTIVE_SEEN=true && \
#debconf-show tzdata && \
#wget -O vscode.deb 'https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64' && \
#apt --yes install ./vscode.deb && rm vscode.deb



RUN pip install xgboost lightgbm seaborn h5py plotly torchviz line_profiler bokeh tqdm pandas ipywidgets python-csv memory_profiler hydra-core boost-histogram uproot4 awkward1 particle debugpy alabaster Babel cached-property certifi chardet cycler docutils gif idna imagesize Jinja2 joblib kiwisolver MarkupSafe packaging Pillow Pygments pyparsing python-dateutil pytz requests scikit-learn scipy six sklearn snowballstemmer Sphinx sphinxcontrib-applehelp sphinxcontrib-devhelp sphinxcontrib-htmlhelp sphinxcontrib-jsmath sphinxcontrib-qthelp sphinxcontrib-serializinghtml threadpoolctl typing-extensions urllib3 wandb spyder pdbpp

RUN wget https://download.jetbrains.com/python/pycharm-community-2019.2.3.tar.gz?_ga=2.141719730.1677997767.1570599993-1937107941.1570599993 && tar xfz pycharm-*.tar.gz* -C /opt/ && rm -r pycharm-*.tar.gz*

